version: "2"
services:
  server:
    image: node:16-slim
    container_name: server
    working_dir: /code
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
      - server_node_modules:/code/node_modules
    environment:
      - TZ=America/New_York
    command: yarn install && yarn start
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    restart: always

volumes:
  server_node_modules:
