name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache-dependency-path: frontend/yarn.lock
        cache: 'yarn'

    - name: Install Frontend Dependencies
      working-directory: frontend
      run: yarn install --frozen-lockfile

    - name: Build Frontend
      working-directory: frontend
      run: CI=false yarn build; cp build/index.html build/404.html
    
    - name: Install Backend Dependencies
      working-directory: frontend
      run: yarn install --frozen-lockfile
    
    - name: Build GraphDB Utils Docs
      run:  npx typedoc --entryPoints ./backend/utils/graphdb/index.d.ts --out ./frontend/build/docs/gdb-utils/
      
    - name: Deploy Frontend to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build

